/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.user.post.summary;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CityPostRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CityPostRecord\",\"namespace\":\"org.user.post.summary\",\"fields\":[{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"rank\",\"type\":\"int\"},{\"name\":\"post_count\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence city;
  @Deprecated public int rank;
  @Deprecated public int post_count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CityPostRecord() {}

  /**
   * All-args constructor.
   */
  public CityPostRecord(java.lang.CharSequence city, java.lang.Integer rank, java.lang.Integer post_count) {
    this.city = city;
    this.rank = rank;
    this.post_count = post_count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return city;
    case 1: return rank;
    case 2: return post_count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: city = (java.lang.CharSequence)value$; break;
    case 1: rank = (java.lang.Integer)value$; break;
    case 2: post_count = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'rank' field.
   */
  public java.lang.Integer getRank() {
    return rank;
  }

  /**
   * Sets the value of the 'rank' field.
   * @param value the value to set.
   */
  public void setRank(java.lang.Integer value) {
    this.rank = value;
  }

  /**
   * Gets the value of the 'post_count' field.
   */
  public java.lang.Integer getPostCount() {
    return post_count;
  }

  /**
   * Sets the value of the 'post_count' field.
   * @param value the value to set.
   */
  public void setPostCount(java.lang.Integer value) {
    this.post_count = value;
  }

  /** Creates a new CityPostRecord RecordBuilder */
  public static org.user.post.summary.CityPostRecord.Builder newBuilder() {
    return new org.user.post.summary.CityPostRecord.Builder();
  }
  
  /** Creates a new CityPostRecord RecordBuilder by copying an existing Builder */
  public static org.user.post.summary.CityPostRecord.Builder newBuilder(org.user.post.summary.CityPostRecord.Builder other) {
    return new org.user.post.summary.CityPostRecord.Builder(other);
  }
  
  /** Creates a new CityPostRecord RecordBuilder by copying an existing CityPostRecord instance */
  public static org.user.post.summary.CityPostRecord.Builder newBuilder(org.user.post.summary.CityPostRecord other) {
    return new org.user.post.summary.CityPostRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for CityPostRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CityPostRecord>
    implements org.apache.avro.data.RecordBuilder<CityPostRecord> {

    private java.lang.CharSequence city;
    private int rank;
    private int post_count;

    /** Creates a new Builder */
    private Builder() {
      super(org.user.post.summary.CityPostRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.user.post.summary.CityPostRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rank)) {
        this.rank = data().deepCopy(fields()[1].schema(), other.rank);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.post_count)) {
        this.post_count = data().deepCopy(fields()[2].schema(), other.post_count);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CityPostRecord instance */
    private Builder(org.user.post.summary.CityPostRecord other) {
            super(org.user.post.summary.CityPostRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rank)) {
        this.rank = data().deepCopy(fields()[1].schema(), other.rank);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.post_count)) {
        this.post_count = data().deepCopy(fields()[2].schema(), other.post_count);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'city' field */
    public java.lang.CharSequence getCity() {
      return city;
    }
    
    /** Sets the value of the 'city' field */
    public org.user.post.summary.CityPostRecord.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.city = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'city' field has been set */
    public boolean hasCity() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'city' field */
    public org.user.post.summary.CityPostRecord.Builder clearCity() {
      city = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'rank' field */
    public java.lang.Integer getRank() {
      return rank;
    }
    
    /** Sets the value of the 'rank' field */
    public org.user.post.summary.CityPostRecord.Builder setRank(int value) {
      validate(fields()[1], value);
      this.rank = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'rank' field has been set */
    public boolean hasRank() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'rank' field */
    public org.user.post.summary.CityPostRecord.Builder clearRank() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'post_count' field */
    public java.lang.Integer getPostCount() {
      return post_count;
    }
    
    /** Sets the value of the 'post_count' field */
    public org.user.post.summary.CityPostRecord.Builder setPostCount(int value) {
      validate(fields()[2], value);
      this.post_count = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'post_count' field has been set */
    public boolean hasPostCount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'post_count' field */
    public org.user.post.summary.CityPostRecord.Builder clearPostCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public CityPostRecord build() {
      try {
        CityPostRecord record = new CityPostRecord();
        record.city = fieldSetFlags()[0] ? this.city : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.rank = fieldSetFlags()[1] ? this.rank : (java.lang.Integer) defaultValue(fields()[1]);
        record.post_count = fieldSetFlags()[2] ? this.post_count : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
