/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.user.post.summary;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserSummaryProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserSummaryProtocol\",\"namespace\":\"org.user.post.summary\",\"types\":[{\"type\":\"record\",\"name\":\"DayCityPost\",\"fields\":[{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"post_count\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"CityPostRecord\",\"fields\":[{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"rank\",\"type\":\"int\"},{\"name\":\"post_count\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"DayCityPostSummary\",\"fields\":[{\"name\":\"citySummary\",\"type\":{\"type\":\"array\",\"items\":\"CityPostRecord\"},\"default\":[]}]},{\"type\":\"record\",\"name\":\"UserPost\",\"fields\":[{\"name\":\"post_date\",\"type\":\"string\"},{\"name\":\"post_count\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"UserPostSummary\",\"fields\":[{\"name\":\"user_id\",\"type\":\"string\"},{\"name\":\"user_city\",\"type\":\"string\"},{\"name\":\"total_posts\",\"type\":\"int\"},{\"name\":\"posts\",\"type\":{\"type\":\"array\",\"items\":\"UserPost\"},\"default\":[]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends UserSummaryProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = org.user.post.summary.UserSummaryProtocol.PROTOCOL;
  }
}